/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kkk_jni_jniMathKit */

#ifndef _Included_com_kkk_jni_jniMathKit
#define _Included_com_kkk_jni_jniMathKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kkk_jni_jniMathKit
 * Method:    getSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_kkk_jni_jniMathKit_getSum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
